/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2010
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/


/*******************************************************************************
 *
 * Filename:
 * ---------
 * AppMsg.h
 *
 * Project:
 * --------
 *
 *
 * Description:
 * ------------
 *
 *
 * Author:
 * -------
 * Cole Xing
 *
 *------------------------------------------------------------------------------
 * $Revision:
 * $Modtime:
 * $Log:
 *
 *******************************************************************************/
#ifndef __APPMSG_H__
#define __APPMSG_H__

#define EVT_START (WM_USER + 0x3100)
#define MSG_START (WM_USER + 0x3200)
 
#define EVT_DVDAP_START (WM_USER + 0x3300)
#define MSG_DVDAP_START (WM_USER + 0x3350)
#define MSG_MSDK_START  (WM_USER + 0x3500)
#define MSG_DVPAGENT_START   (WM_USER + 0x3700)
#define MSG_MMP_START        (WM_USER + 0x3900) 

#define MSG_OVERLAY_START    (WM_USER + 0x4100)

#define MSG_FRONT_REAR_START (WM_USER + 0X5100)

#define MSG_QUERY_FRONT_REAR_SOURCE  (WM_USER + 0x6100)
#define MSG_ANSWER_FRONT_REAR_SOURCE (WM_USER + 0x6101)

#define DBT_DEVICEARRIVAL        0x8000
#define DBT_DEVICEREMOVECOMPLETE 0x8004
// Message define


#define WINCE_SOUND_MAX_VOLUME    100
#define WINCE_SOUND_MIN_VOLUME    0


#define WM_NAVI_PROCESS_HANDLE (WM_USER + 0X13)
#define WM_NAVI_AUDIO_START_STOP 0x3644
#define WM_NAVI_SET_VOLUME     (WM_USER + 0X15)

enum
{
    MSG_APP_INTERNAL_CMD = MSG_START,
   // MSG_SETTINGS_CHANGE,
    MSG_HOME_AND_MMP,
    MSG_HOME_AND_SETTINGS,
    MSG_HOME_NEMA,
    MSG_HOME_AND_BT,
	MSG_HOME_AND_OVERLAY,
	MSG_ENTER_TOUCH_CALI,

};

// DVDAP Event define
enum
{
    EVT_DVDAP_NOKEY= EVT_DVDAP_START,
 
    EVT_DVDAP_UARTOK,
    EVT_DVDAP_DVDDISPLAY,
    EVT_DVDAP_DVDUPDATE_TIME,
    EVT_DVDAP_DVDFLUPDATE_TIME,
    EVT_DVDAP_BLACKBG
};
// DVDAP Message define
enum
{
    MSG_DVDAP_VIDEOPANEL_RELEASE = MSG_DVDAP_START,
    MSG_DVDAP_EXIT_PLAYCAM ,
    MSG_DVDAP_HIDE_PLAYCAM ,
    MSG_DVDAP_SHOW_PLAYCAM,
    MSG_DVDAP_STOP_PLAYCAM,
    MSG_DVDAP_PLAY_PLAYCAM,
    MSG_DVDAP_DVDCMD

};

// u4Param1 for MSG_HOME_AND_OVERLAY
enum
{
//VIDEO
    MSG_SETTINGS_CHANGE_VIDEO_BRIGHTNESS,
    MSG_SETTINGS_CHANGE_VIDEO_CONTRAST,
    MSG_SETTINGS_CHANGE_VIDEO_HUE,
    MSG_SETTINGS_CHANGE_VIDEO_BACKLIGHT,	
//AUDIO
    MSG_SETTINGS_CHANGE_AUDIO_VOLUME,
    MSG_SETTINGS_CHANGE_AUDIO_BALANCE,
    MSG_SETTINGS_CHANGE_AUDIO_EQ,
    MSG_SETTINGS_CHANGE_AUDIO_KEYBEEP,
//LOGO

//TIME
	MSG_SETTINGS_CHANGE_TIME_TIMEFORMAT,
	MSG_SETTINGS_CHANGE_TIME_AUTOTIME,
    MSG_SETTINGS_CHANGE_TIME_DATE_Y,
	MSG_SETTINGS_CHANGE_TIME_TIME_H,
    MSG_SETTINGS_CHANGE_TIME_DATE_M,
    MSG_SETTINGS_CHANGE_TIME_DATE_D,
	MSG_SETTINGS_CHANGE_TIME_TIME_M,
//SYS
    MSG_SETTINGS_CHANGE_SYS_NAVIPATH,
    MSG_SETTINGS_CHANGE_SYS_CALIBRATION,
    MSG_SETTINGS_CHANGE_SYS_RESET,

    MSG_SETTINGS_CHANGE_HWND,
};

// u4Param2 for MSG_SETTINGS_CHANGE => MSG_SETTINGS_CHANGE_TIME_TIMEFORMAT
enum
{
    MSG_SETTINGS_CHANGE_TIME_TIMEFORMAT_12 = 0,
    MSG_SETTINGS_CHANGE_TIME_TIMEFORMAT_24,
};

// u4Param1 for MSG_HOME_AND_MMP
enum
{
//Home to MMP
    MSG_HOME_AND_MMP_SWITCH_TO,          //0: DVD,  1: USB,  3: Card
    MSG_HOME_AND_MMP_EJECT_DISK,         
    MSG_HOME_AND_MMP_PLAY,               //0: Play/Pause, 1: Next, 2: Pre 
    MSG_HOME_AND_MMP_EXIT,
    MSG_HOME_AND_MMP_SET_VOL,            // 0 - 20
	MSG_HOME_AND_MMP_SHOW_OVERLAY,
    MSG_HOME_AND_MMP_HIDE_OVERLAY,
//MMP to Home
    MSG_HOME_AND_MMP_DISK_NOTIFY,        //0: Disk out, 1: Disk in
    MSG_HOME_AND_MMP_SD_USB_NOTIFY,         //0x00000000: SD out, 0x00010000: SD in, 0x00000000: USB out, 0x00000001: USB in
    MSG_HOME_AND_MMP_DVDAPP_HWND,


    MSG_HOME_AND_MMP_BACK_CAR_START,
    MSG_HOME_AND_MMP_BACK_CAR_FINISH,
    MSG_HOME_AND_MMP_BT_PAUSE_RESUME_AUDIO,  // 暂停/播放,0为puase,1为play
};

// u4Param2 for MSG_HOME_AND_MMP => MSG_HOME_AND_MMP_SWITCH_TO
enum
{
    //Home to MMP
    MSG_HOME_AND_MMP_SWITCH_TO_DVD,
    MSG_HOME_AND_MMP_SWITCH_TO_USB,
    MSG_HOME_AND_MMP_SWITCH_TO_CARD,
};

// u4Param2 for MSG_HOME_AND_MMP => MSG_HOME_AND_MMP_PLAY
enum
{
    //Home to MMP
    MSG_HOME_AND_MMP_PLAY_PLAY_PAUSE,
    MSG_HOME_AND_MMP_PLAY_NEXT,
    MSG_HOME_AND_MMP_PLAY_PRE,
};

// u4Param2 for MSG_HOME_AND_MMP => MSG_HOME_AND_MMP_DISK_NOTIFY/MSG_HOME_AND_MMP_USB_NOTIFY
enum
{
    MSG_HOME_AND_MMP_DISK_SD_USB_OUT,
    MSG_HOME_AND_MMP_DISK_SD_USB_IN,
};

// u4Param1 for MSG_HOME_AND_BT
enum
{
    MSG_HOME_AND_BT_SHOW,
};


// u4Param1 for MSG_HOME_AND_SETTINGS
enum
{
    MSG_HOME_AND_SETTINGS_SHOW,
    MSG_HOME_AND_SETTINGS_HIDE,
    MSG_HOME_AND_SETTINGS_SET_VOL,
};



// u4Param1 for MSG_HOME_NEMA
enum
{
    MSG_HOME_NEMA_DATE,
    MSG_HOME_NEMA_TIME,
    MSG_HOME_NEMA_STATUS
};


// u4Param1 for MSG_HOME_AND_BT
enum
{
    MSG_HOME_AND_BT_SHOW_BT = 0,
    MSG_HOME_AND_BT_HIDE_BT,
    MSG_HOME_AND_BT_REQUEST_SHOW,
    MSG_HOME_AND_BT_REQUEST_HIDE,
    MSG_HOME_AND_BT_REQUEST_SHOW_OK,
    MSG_HOME_AND_BT_ON,
    MSG_HOME_AND_BT_OFF,
	MSG_HOME_AND_BT_HWND,
    MSG_HOME_AND_BT_WANT_SHOW,
    MSG_HOME_AND_BT_CALL_BEGIN,
    MSG_HOME_AND_BT_CALL_END,
    MSG_HOME_AND_BT_REQUEST_HIDE_OK,
    MSG_HOME_AND_BT_HIDE_OVERLAY,
    MSG_HOME_AND_BT_PAUSE_OTHER_AUDIO,
    MSG_HOME_AND_BT_RESUME_OTHER_AUDIO,
	MSG_HOME_AND_BT_QUERY_A2DP_STATE		// 1 is playing/pause, 0 is not active
};


// MMP Event define
enum
{
    WM_MSDK_MEDIAGRAPH = MSG_MMP_START,
    WM_DVPAGENT_EVENT,
    WM_IMAGEDECODER_EVENT,  // for JPG decode event
	WM_MMP_HOME_PARAM,
	WM_MMP_LOADING_FINISH,
	WM_MMP_MEDIA_DISATTACHED,
};

// OVERLAY Event define
enum
{
    WM_OVERLAY_MSG = MSG_OVERLAY_START,
	WM_OVERLAY_VIEW_MUTE,
	WM_OVERLAY_VIEW_VOLUME,
	WM_OVERLAY_CHANGE_VIEW,
};

// u4Param1 for WM_OVERLAY_MSG
enum
{
    MSG_VOLUME_TIMER,
};


//Snail(MTK71174) add for Front and Rear
enum
{
    MSG_HOME_AND_A2DP_QUERY = MSG_FRONT_REAR_START, // A2DP 请求播放 
    MSG_HOME_AND_A2DP_CHANGE, // 切换到A2DP播放
    MSG_HOME_AND_A2DP_REPLY,// HOME 答复 A2DP 当前是否可以播放
    MSG_HOME_AND_APP_IN,  // 开始运行APP
    MSG_HOME_AND_APP_EXIT, // 退出APP
    MSG_HOME_AND_APP_STOP, // 切换source源，home发此消息给当前播放的APP要求当前APP退出
    MSG_HOME_AND_APP_START, // 同一source，home 发此消息给当前播放的APP
    MSG_HOME_AND_APP_REAR, // 给后排source 发消息
    MSG_HOME_AND_APP_AVSWITCH,   // home查询是否能切换成功
    MSG_HOME_AND_APP_INFIL, // USB后排进入filelist界面
};

//Snail(MTK71174) add for wparam 
enum
{
    MSG_WPARAM_NULL,
    MSG_WPARAM_FORNT, // 当前在前排播放
    MSG_WPARAM_REAR,  // 当前在后排播放
    MSG_WPARAM_FORNT_AND_REAR, // 当前在前后排播放
};

//Snail(MTK71174) add for lparam
enum
{
    MSG_LPARAM_NULL, // 当前没有播放任何source
    MSG_LPARAM_DVP, // 当前在播放DVP
    MSG_LPARAM_SD, // 当前在播放SD
    MSG_LPARAM_USB, // 当前在播放USB
    MSG_LPARAM_AVIN1, // 当前在播放AVIN1
    MSG_LPARAM_AVIN2, // 当前在播放AVIN2
    MSG_LPARAM_AVIN3, // 当前在播放AVIN3
    MSG_LPARAM_AVIN4, // 当前在播放AVIN4
    MSG_LPARAM_AVIN5, // 当前在播放AVIN5
    MSG_LPARAM_A2DP, // 当前在播放A2DP
};

//Snial(MTK71174) add for A2DP
enum
{
    MSG_WPARAM_A2DP_PLAY, // 当前可以播放A2DP
    MSG_WPARAM_A2DP_NOPLAY,// 当前不可以播放A2DP
    MSG_WPARAM_A2DP_NO_OTHER_AUDIO  // 其他source源退出时
};
#endif