#pragma once

extern "C" BOOL WINAPI CreatePhoneLinkProcess(LPCWSTR pszImageName,LPCWSTR pszCmdLine,LPPROCESS_INFORMATION pProcInfo);
extern "C" BOOL WINAPI CheckRev();


//to register and get user message
#define GET_USER_MESSAGE_ID(name) ::RegisterWindowMessage(name)

#define UWM_PHONELINK_EXIT   _T("UWM_PHONELINK_EXIT-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_DISCONNECT _T("UWM_PHONELINK_DISCONNECT-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_CONNECTING _T("UWM_PHONELINK_CONNECTING-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_CONNECTED _T("UWM_PHONELINK_CONNECTED-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_CONNECT_FAIL _T("UWM_PHONELINK_CONNECT_FAIL-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_START _T("UWM_PHONELINK_START-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_STOP _T("UWM_PHONELINK_STOP-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_HAND_CLIENT   _T("UWM_PHONELINK_HAND_CLIENT-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_HAND_MAIN   _T("UWM_PHONELINK_HAND_MAIN-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_CLIENT_TRANS   _T("UWM_PHONELINK_CLIENT_TRANS-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_MAIN_TRANS   _T("UWM_PHONELINK_MAIN_TRANS-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_INSTALL   _T("UWM_PHONELINK_INSTALL-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_INSTALL_OK   _T("UWM_PHONELINK_INSTALL_OK-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_RESET   _T("UWM_PHONELINK_RESET-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_RESET_OK   _T("UWM_PHONELINK_RESET_OK-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_KEY_HOME   _T("UWM_PHONELINK_KEY_HOME-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_KEY_MENU   _T("UWM_PHONELINK_KEY_MENU-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_KEY_BACK   _T("UWM_PHONELINK_KEY_BACK-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_KEY_LAND   _T("UWM_PHONELINK_KEY_LAND-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_NO_LICENSE   _T("UWM_PHONELINK_NO_LICENSE-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_NO_USB_DEBUG   _T("UWM_PHONELINK_NO_USB_DEBUG-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_REQUEST_STATE   _T("UWM_PHONELINK_REQUEST_STATE-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_RETURN_STATE   _T("UWM_PHONELINK_RETURN_STATE-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
#define UWM_PHONELINK_SCREEN_OFF   _T("UWM_PHONELINK_SCREEN_OFF-{7049499B-0480-44f9-BF71-4AE91FA0443C}")

const UINT ID_UWM_PHONELINK_EXIT = GET_USER_MESSAGE_ID(UWM_PHONELINK_EXIT);
const UINT ID_UWM_PHONELINK_DISCONNECT = GET_USER_MESSAGE_ID(UWM_PHONELINK_DISCONNECT);
const UINT ID_UWM_PHONELINK_CONNECTING = GET_USER_MESSAGE_ID(UWM_PHONELINK_CONNECTING);
const UINT ID_UWM_PHONELINK_CONNECTED = GET_USER_MESSAGE_ID(UWM_PHONELINK_CONNECTED);
const UINT ID_UWM_PHONELINK_CONNECT_FAIL = GET_USER_MESSAGE_ID(UWM_PHONELINK_CONNECT_FAIL);
const UINT ID_UWM_PHONELINK_START = GET_USER_MESSAGE_ID(UWM_PHONELINK_START);
const UINT ID_UWM_PHONELINK_STOP = GET_USER_MESSAGE_ID(UWM_PHONELINK_STOP);
const UINT ID_UWM_PHONELINK_HAND_CLIENT = GET_USER_MESSAGE_ID(UWM_PHONELINK_HAND_CLIENT);
const UINT ID_UWM_PHONELINK_HAND_MAIN = GET_USER_MESSAGE_ID(UWM_PHONELINK_HAND_MAIN);
const UINT ID_UWM_PHONELINK_CLIENT_TRANS = GET_USER_MESSAGE_ID(UWM_PHONELINK_CLIENT_TRANS);
const UINT ID_UWM_PHONELINK_MAIN_TRANS = GET_USER_MESSAGE_ID(UWM_PHONELINK_MAIN_TRANS);
const UINT ID_UWM_PHONELINK_INSTALL = GET_USER_MESSAGE_ID(UWM_PHONELINK_INSTALL);
const UINT ID_UWM_PHONELINK_INSTALL_OK = GET_USER_MESSAGE_ID(UWM_PHONELINK_INSTALL_OK);
const UINT ID_UWM_PHONELINK_RESET = GET_USER_MESSAGE_ID(UWM_PHONELINK_RESET);
const UINT ID_UWM_PHONELINK_RESET_OK = GET_USER_MESSAGE_ID(UWM_PHONELINK_RESET_OK);
const UINT ID_UWM_PHONELINK_KEY_HOME = GET_USER_MESSAGE_ID(UWM_PHONELINK_KEY_HOME);
const UINT ID_UWM_PHONELINK_KEY_MENU = GET_USER_MESSAGE_ID(UWM_PHONELINK_KEY_MENU);
const UINT ID_UWM_PHONELINK_KEY_BACK = GET_USER_MESSAGE_ID(UWM_PHONELINK_KEY_BACK);
const UINT ID_UWM_PHONELINK_KEY_LAND = GET_USER_MESSAGE_ID(UWM_PHONELINK_KEY_LAND);
const UINT ID_UWM_PHONELINK_NO_LICENSE = GET_USER_MESSAGE_ID(UWM_PHONELINK_NO_LICENSE);
const UINT ID_UWM_PHONELINK_NO_USB_DEBUG = GET_USER_MESSAGE_ID(UWM_PHONELINK_NO_USB_DEBUG);
const UINT ID_UWM_PHONELINK_REQUEST_STATE = GET_USER_MESSAGE_ID(UWM_PHONELINK_REQUEST_STATE);
const UINT ID_UWM_PHONELINK_RETURN_STATE = GET_USER_MESSAGE_ID(UWM_PHONELINK_RETURN_STATE);
const UINT ID_UWM_PHONELINK_SCREEN_OFF = GET_USER_MESSAGE_ID(UWM_PHONELINK_SCREEN_OFF);

// wParam : 0 ~ 隐藏  1 ~ 显示
#define UWM_PHONELINK_CONTROL_SHOW   _T("UWM_PHONELINK_CONTROL_SHOW-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
const UINT ID_UWM_PHONELINK_CONTROL_SHOW = GET_USER_MESSAGE_ID(UWM_PHONELINK_CONTROL_SHOW);

// 当车机端正在显示禁止使用互联界面时，点击一个按键进入互联，点击按键后，
// 传输以下message给phonelink启动手机端驾驶模式的app：
#define UWM_PHONELINK_START_DRIVER_APP   _T("UWM_PHONELINK_START_DRIVER_APP-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
const UINT ID_UWM_PHONELINK_START_DRIVER_APP = GET_USER_MESSAGE_ID(UWM_PHONELINK_START_DRIVER_APP);


#define UWM_PHONELINK_QUIT   _T("UWM_PHONELINK_QUIT-{7049499B-0480-44f9-BF71-4AE91FA0443C}")
const UINT ID_UWM_PHONELINK_QUIT = GET_USER_MESSAGE_ID(UWM_PHONELINK_QUIT);


// The thread Bin Data Copy from YG_API.DLL
// It need to read flash data
//TRANS type
#define TRANS_READ  0
#define TRANS_WRITE  1
#define TRANS_READ_FEEDBACK  2
#define TRANS_WRITE_FEEDBACK  3

//TRANS state
#define TRANS_STATE_SUCCESS  0
#define TRANS_STATE_FAIL  1

#define PHONELINK_APP_NAME     _T("PhoneLinkClient.exe")
#define PHONELINK_RUN_PW_STRING _T("YIGUANG52K05K43VM")

typedef struct TRANS_DATA_STRU 
{
	int type;
	int state;
	int count;          // nBytes to read/write
	UCHAR  buf[16];           // Buffer
	UCHAR  device_addr; 
	UCHAR  sub_addr;
}TRANS_DATA;


class CPhoneLink
{
public:
	CPhoneLink(void);
	~CPhoneLink(void);

public:
	static CPhoneLink* GetInstance();
	static void ShowWindow(BOOL bShow);
	static BOOL LoadPhoneLink();
	BOOL Initialize(HWND hWnd);
	void Uninitialize();
	// 处理phonelink程序发来的消息,如果处理了返回TRUE,否则返回FALSE
	BOOL HandleMessage(UINT message, WPARAM wParam, LPARAM lParam);
	// 向phonelink发消息
	void PostMessage2Phonelink(UINT message, WPARAM wParam, LPARAM lParam);

	void OnConnect(BOOL bConnect);

	/* source control */
	void LaunchSrc();
	void StopSrc();

	BOOL IsConnected();
	BOOL IsConnecting();

	// 临时打开或关闭声音通道 for RDS
	void OpenAudio();
	void CloseAudio();

protected:

	HWND m_hwnd;	// phonelink app的窗口
	BOOL m_bIsConnected;
	BOOL m_bIsConnecting;
	BOOL m_bInitalized;

	// 代理phonelink的请求数据,通过I2C发给加密芯片，获取返回的数据
	BOOL HandlePhonelinkData();
	// 将数据发送phonelink
	void SendDataToPhonelink();
	TRANS_DATA m_data_in;
	TRANS_DATA m_data_out;


};
